import { staticImplements } from '../util/staticImplements';
import {
  IDatabaseModel,
  IDatabaseModelStatic
} from '../interfaces/IDatabaseModel';

import { DatabaseController as db } from '../controllers/database';
import { QueryResult } from 'pg';

import { Product } from './product';
import { Cart } from './cart';
import { promises } from 'dns';

//@staticImplements<IDatabaseModelStatic>()
class CartProduct implements IDatabaseModel {
  id: number;
  createdAt: Date | undefined = undefined; // so we can sort by whichever products were added first
  belongsToCart: number;
  quantity: number;
  product: Product = new Product('', '', '', 0);

  static tableName = 'CartProducts';

  static async init(databaseController: db): Promise<QueryResult> {
    return db.query(
      `CREATE TABLE IF NOT EXISTS ${CartProduct.tableName}(
          id INT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          belongsToCart INT NOT NULL REFERENCES ${Cart.tableName}(id) ON DELETE CASCADE ON UPDATE CASCADE,
          productID INT NOT NULL REFERENCES ${Product.tableName}(id) ON DELETE CASCADE ON UPDATE CASCADE,
          quantity INT NOT NULL,
          updatedAt TIMESTAMPTZ NOT NULL,
          createdAt TIMESTAMPTZ NOT NULL
        )`
    );
  }

  constructor(
    belongsToCart: number,
    quantity: number,
    createdAt?: Date,
    id?: number
  ) {
    this.id = id !== undefined ? id : NaN;
    this.createdAt = createdAt !== undefined ? createdAt : undefined;
    this.belongsToCart = belongsToCart;
    this.quantity = quantity;
  }

  async setup(productID: number) {
    return Product.findByID(productID).then(
      product => (this.product = product)
    );
  }

  async save(): Promise<QueryResult> {
    // Does the cartItem exist in the app
    let result = !isNaN(this.id);

    // Even if so, does it for some reason not exist in the DB?
    // Maybe someone manually inserted a faulty ID into the URL
    if (result) {
      await db
        .query(
          `SELECT EXISTS(select 1 from ${Product.tableName} where id=$1)`,
          [this.product.id]
        )
        .then(res => {
          result = res.rows[0].exists;
        });
    }

    const now = new Date();
    if (!result) {
      return new Promise<QueryResult<any>>(res => {
        db.query(
          `INSERT INTO ${CartProduct.tableName} (belongsToCart, productID, quantity, updatedAt, createdAt) VALUES ($1, $2, $3, $4, $4) RETURNING *`,
          [this.belongsToCart, this.product.id, this.quantity, now]
        ).then(result => {
          this.id = result.rows[0].id;
          res(result);
        });
      });
    } else {
      return db.query(
        `UPDATE ${CartProduct.tableName} SET quantity=$1, updatedAt=$2 WHERE id=$3`,
        [this.quantity, now, this.id]
      );
    }
  }

  delete(): Promise<QueryResult> {
    return db.query(`DELETE FROM ${CartProduct.tableName} WHERE id=$1`, [
      this.id
    ]);
  }

  modifyQuantity(newQuantity: number): Promise<void> {
    return new Promise<void>(async resolve => {
      if (newQuantity === 0) {
        await this.delete();
      } else {
        this.quantity = newQuantity;
        await this.save();
      }
      resolve();
    });
  }

  static fetchAllBelongingToCart(cartID: number): Promise<CartProduct[]> {
    return new Promise<CartProduct[]>(resolve => {
      db.query(
        `SELECT * FROM ${CartProduct.tableName} WHERE belongsToCart=$1`,
        [cartID]
      )
        .then(async result => {
          const cartProducts: CartProduct[] = [];
          for (const row of result.rows) {
            await this.createInstanceFromDB(row).then(result => {
              cartProducts.push(result!);
            });
          }
          resolve(cartProducts);
        })
        .catch(err => console.log(err));
    });
  }

  private static async createInstanceFromDB(
    dbProduct: any
  ): Promise<CartProduct | undefined> {
    if (dbProduct === undefined) {
      return undefined;
    }

    const cartProduct = new CartProduct(
      dbProduct.belongsToCart,
      dbProduct.quantity,
      dbProduct.createdat, // so we can sort by whichever products were added first
      dbProduct.id
    );

    await cartProduct.setup(dbProduct.productid);
    return cartProduct;
  }
}

export { CartProduct };
